#!/usr/bin/env python3
"""rSLDS (Linderman et al., AISTATS 2017) baseline on nascar / toyark13 / mocap6.

Faithful port of ``recurrent-slds-master/examples/nascar.py`` against the
vendored ``shs_demo/rslds`` package, generalised to multiple sequences and the
three suite datasets.  Pipeline, exactly as in the reference:

    PCA (whitened) -> x_init
    sticky AR-HMM Gibbs on x_init -> z_init
    decision-list fit -> state permutation + recurrence-weight init
    {rslds | rslds-ro | sticky-rslds} Polya-Gamma Gibbs

ENVIRONMENT -- read this first
------------------------------
The 2017 stack (pybasicbayes / pyhsmm / autoregressive / pylds / pyslds /
pypolyagamma) contains Cython extensions and numpy<1.24 idioms that DO NOT
build on python>=3.10 (see ``environment-baselines.yml`` next to this file for
a working conda recipe, python 3.8).  This script fails fast with that message
when the stack is absent.  Results land in the same ``results/<dataset>/``
folder as the other runners, so you can fit here and aggregate with
``make_figures.py`` in either environment.

NASCAR is read from ``data_cache/`` (generated by datasets.py), so the legacy
environment sees byte-identical data to the modern one.

Examples
--------
    python run_rslds.py --dataset nascar --samples 1000
    python run_rslds.py --dataset toyark13 --nseq 12 --dlatent 3 --variant rslds-ro
    python run_rslds.py --dataset mocap6 --dlatent 6 --variant sticky-rslds
"""
import argparse
import pathlib
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))                    # compare/ modules
sys.path.insert(0, str(HERE.parents[0]))         # shs_demo/ -> vendored rslds

import datasets                                   # noqa: E402
from io_utils import Timer, save_result           # noqa: E402
from metrics import all_metrics                   # noqa: E402

try:
    from pybasicbayes.distributions import Regression, Gaussian, \
        DiagonalRegression, AutoRegression
    from pyhsmm.util.general import relabel_by_permutation
    from autoregressive.models import ARWeakLimitStickyHDPHMM
    from pyslds.util import get_empirical_ar_params
    from pypolyagamma.distributions import MultinomialRegression
    from rslds.decision_list import DecisionList
    from rslds.models import PGRecurrentSLDS, StickyPGRecurrentSLDS, \
        PGRecurrentOnlySLDS, StickyPGRecurrentOnlySLDS
except ImportError as e:
    sys.exit(
        f"[rslds] missing legacy dependency: {e}\n"
        "The 2017 rSLDS stack requires python<=3.8 / numpy<1.24 "
        "(Cython pins).  Create the environment in "
        "compare/environment-baselines.yml and rerun this script there;\n"
        "its results npz will drop into the shared results/ folder for "
        "make_figures.py.")

DEFAULTS = dict(
    nascar=dict(K=4, dlatent=2, samples=1000, variant="rslds"),
    toyark13=dict(K=16, dlatent=3, samples=1000, variant="rslds"),
    mocap6=dict(K=16, dlatent=6, samples=1000, variant="rslds"),
)


def fit_pca(Ycat, D_latent, whiten=True):
    from sklearn.decomposition import PCA
    model = PCA(n_components=D_latent, whiten=whiten)
    x = model.fit_transform(Ycat)
    C = model.components_.T
    if whiten:
        C = np.sqrt(model.explained_variance_) * C
    return x, np.column_stack((C, model.mean_[:, None]))


def fit_arhmm(x_list, K, D_latent, n_samples, affine=True):
    print("[rslds] initializing with sticky AR-HMM Gibbs")
    hyp = dict(nu_0=D_latent + 2, S_0=np.eye(D_latent),
               M_0=np.hstack((np.eye(D_latent),
                              np.zeros((D_latent, int(affine))))),
               K_0=np.eye(D_latent + affine), affine=affine)
    hyp = get_empirical_ar_params(x_list, hyp)
    dds = [AutoRegression(A=np.column_stack((0.99 * np.eye(D_latent),
                                             np.zeros((D_latent, int(affine))))),
                          sigma=np.eye(D_latent), **hyp) for _ in range(K)]
    init_d = Gaussian(nu_0=D_latent + 2, sigma_0=np.eye(D_latent),
                      mu_0=np.zeros(D_latent), kappa_0=1.0)
    arhmm = ARWeakLimitStickyHDPHMM(init_state_distn='uniform',
                                    init_emission_distn=init_d,
                                    obs_distns=dds,
                                    alpha=3.0, kappa=10.0, gamma=3.0)
    for x in x_list:
        arhmm.add_data(x)
    for _ in range(n_samples):
        arhmm.resample_model()
    z_init = [np.concatenate(([0], s.stateseq)) for s in arhmm.states_list]
    return z_init


def make_parameters(K, D_latent, D_obs, C_init):
    init_dyn = [Gaussian(mu=np.zeros(D_latent), sigma=np.eye(D_latent),
                         nu_0=D_latent + 2, sigma_0=3. * np.eye(D_latent),
                         mu_0=np.zeros(D_latent), kappa_0=1.0)
                for _ in range(K)]
    dyn = [Regression(nu_0=D_latent + 2, S_0=1e-4 * np.eye(D_latent),
                      M_0=np.hstack((np.eye(D_latent),
                                     np.zeros((D_latent, 1)))),
                      K_0=np.eye(D_latent + 1)) for _ in range(K)]
    emis = DiagonalRegression(D_obs, D_latent + 1, A=C_init.copy(),
                              sigmasq=np.ones(D_obs), alpha_0=2.0, beta_0=2.0)
    return init_dyn, dyn, emis


def build_model(variant, K, D_latent, D_obs, C_init, dl_reg):
    init_dyn, dyn, emis = make_parameters(K, D_latent, D_obs, C_init)
    common = dict(init_state_distn='uniform', init_dynamics_distns=init_dyn,
                  dynamics_distns=dyn, emission_distns=emis)
    if variant == "rslds":
        return PGRecurrentSLDS(
            trans_params=dict(sigmasq_A=10000., sigmasq_b=10000.,
                              A=np.hstack((np.zeros((K - 1, K)), dl_reg.A)),
                              b=dl_reg.b),
            fixed_emission=False, **common)
    if variant == "sticky-rslds":
        return StickyPGRecurrentSLDS(
            D_in=D_latent,
            trans_params=dict(sigmasq_A=10000., sigmasq_b=10000., kappa=100.,
                              A=np.hstack((np.zeros((K - 1, K)), dl_reg.A)),
                              b=dl_reg.b),
            fixed_emission=False, **common)
    if variant == "rslds-ro":
        return PGRecurrentOnlySLDS(
            trans_params=dict(sigmasq_A=10000., sigmasq_b=10000.,
                              A=dl_reg.A, b=dl_reg.b),
            fixed_emission=False, **common)
    if variant == "sticky-rslds-ro":
        return StickyPGRecurrentOnlySLDS(
            D_in=D_latent,
            trans_params=dict(sigmasq_A=10000., sigmasq_b=10000., kappa=100.,
                              A=dl_reg.A, b=dl_reg.b),
            fixed_emission=False, **common)
    raise ValueError(variant)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", required=True, choices=sorted(datasets.LOADERS))
    ap.add_argument("--nseq", type=int, default=None)
    ap.add_argument("--K", type=int, default=None)
    ap.add_argument("--dlatent", type=int, default=None)
    ap.add_argument("--samples", type=int, default=None)
    ap.add_argument("--init-samples", type=int, default=200,
                    help="AR-HMM initialisation Gibbs iterations")
    ap.add_argument("--variant", default=None,
                    choices=["rslds", "rslds-ro", "sticky-rslds",
                             "sticky-rslds-ro"])
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--data-seed", type=int, default=0,
                    help="nascar: pins the synthetic data realisation "
                         "(shared across models and seeds); --seed varies "
                         "initialisation only")
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--tag", default=None, help="result file stem")
    args = ap.parse_args()

    cfg = dict(DEFAULTS[args.dataset])
    for k in ("K", "dlatent", "samples", "variant"):
        v = getattr(args, k)
        if v is not None:
            cfg[k] = v
    if args.quick:
        cfg["samples"], args.init_samples = 100, 50
    tag = args.tag or ("rslds" if cfg["variant"] == "rslds"
                       else f"rslds_{cfg['variant'].replace('rslds', '').strip('-_') or cfg['variant']}")

    np.random.seed(args.seed)

    load_kw = {}
    if args.dataset == "toyark13":
        load_kw["n_seq"] = args.nseq or 12
    if args.dataset == "nascar":
        load_kw["n_seq"] = args.nseq or 5
        load_kw["seed"] = args.data_seed
    bundle = datasets.load(args.dataset, **load_kw)
    K, D_latent = cfg["K"], cfg["dlatent"]
    D_obs = bundle["D"]
    z_true = np.concatenate(bundle["z_true"])
    Ycat = np.concatenate(bundle["seqs"], 0)
    dr = bundle["doc_range"]

    print(f"[rslds] {args.dataset}: {len(bundle['seqs'])} seqs, D_obs={D_obs}, "
          f"K={K}, D_lat={D_latent}, variant={cfg['variant']}, "
          f"{cfg['samples']} Gibbs samples")

    with Timer() as tm:
        # 1. PCA init
        x_cat, C_init = fit_pca(Ycat, D_latent)
        x_list = [x_cat[dr[i]:dr[i + 1]].copy() for i in range(len(dr) - 1)]

        # 2. sticky AR-HMM init
        z_list = fit_arhmm(x_list, K, D_latent, args.init_samples)

        # 3. decision list -> permutation + recurrence init
        dlist = DecisionList(K, D_latent)
        dlist.fit(np.vstack([x[:-1] for x in x_list]),
                  np.concatenate([z[1:] for z in z_list]))
        dl_reg = MultinomialRegression(1, K, D_latent)
        dl_reg.A = dlist.weights.copy()
        dl_reg.b = dlist.biases[:, None].copy()
        z_list = [relabel_by_permutation(z, np.argsort(dlist.permutation))
                  for z in z_list]

        # 4. rSLDS Gibbs
        model = build_model(cfg["variant"], K, D_latent, D_obs, C_init, dl_reg)
        for i in range(len(dr) - 1):
            y = bundle["seqs"][i]
            model.add_data(y, inputs=np.ones((len(y), 1)),
                           mask=np.ones_like(y, dtype=bool))
            model.states_list[i].stateseq = z_list[i].astype(np.int32)
            model.states_list[i].gaussian_states = x_list[i]
        print("[rslds] initializing dynamics with Gibbs")
        for _ in range(100):
            model.resample_dynamics_distns()
        lps = []
        for itr in range(cfg["samples"]):
            model.resample_model()
            lps.append(model.log_likelihood())
            if (itr + 1) % 100 == 0:
                print(f"    gibbs {itr + 1}/{cfg['samples']} "
                      f"ll={lps[-1]:.1f}", flush=True)
        z_pred = np.concatenate([s.stateseq for s in model.states_list])
        x_fit = np.concatenate([s.gaussian_states for s in model.states_list])

    m, _ = all_metrics(z_true, z_pred)
    print(f"[rslds] {args.dataset}: used={m['K_used']}/{K} "
          f"hamming={m['hamming']:.3f} m2o={m['m2o']:.3f} "
          f"nmi={m['nmi']:.3f} ({tm.elapsed:.0f}s)")

    params = dict(vars(args), **cfg)
    save_result(bundle["name"], tag, z_pred, dr, tm.elapsed, params,
                objective=np.asarray(lps),
                x_latent=(x_fit if D_latent == 2 else None))


if __name__ == "__main__":
    main()
